name: Deploy to GitHub Pages

on:
  # Activa el flujo de trabajo cada vez que hagas push a la rama `main`
  # Usando un nombre de rama diferente? Reemplaza `main` con el nombre de tu rama
  push:
    branches: [ main ]
  # Te permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones en GitHub.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
      - name: Install
        shell: "bash"
        working-directory: ./docs
        run: npm install
      - name: Build
        shell: "bash"
        working-directory: ./docs
        run: BUILD_VERSION=${{ github.ref_name }} npm run build
      - name: Checkout branch
        run: |
          git fetch origin
          git checkout gh-pages
      - name: Copy dist folder
        run: |
          mkdir -p ${{ github.ref_name }}
          cp -r docs/dist/* ${{ github.ref_name }}/
      - name: Commit and push
        run: |
          git config user.name "jhreyess"
          git config user.email "josue.hreyess@gmail.com"
          git add ${{ github.ref_name }}
          git commit -m "Update files" --allow-empty
          git push origin gh-pages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
